// Generated by Wrangler by running `wrangler types ./types/worker-configuration.d.ts --experimental-include-runtime ./types/runtime.d.ts`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: "local" | "staging" | "production";
}
