// Generated by Wrangler by running `wrangler types ./types/worker-configuration.d.ts --experimental-include-runtime ./types/runtime.d.ts`

interface Env {
	ENVIRONMENT: "local" | "staging" | "production";
	OPENAUTH_ISSUER: "http://localhost:8788" | "https://openauth-wrangler-worker-staging.devxo.workers.dev" | "https://openauth-wrangler-worker-production.devxo.workers.dev";
	WORKER: Fetcher;
	ASSETS: Fetcher;
}
